In [2]:
#Question 1: Delete unnamed columns

#import the pandas package
import pandas as pd

#Read the data in csv format
df = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv", sep=',')

#Print first 5 rows of data to see the header/contnets
print("Dataframe before removing unnamed columns:\n", df.head())

#Iterate through the list of columns to find the unnamed columns
for col in df.columns:
    #Check if thee current column is unnamed column
    if col.find('Unnamed') == 0:
        #If the current column is unnamed column, drop it from the original dataframe using inplace = True
        df.drop([col], axis = 1, inplace = True)
        
#Print the first 5 rows of data to see if the unnamed columns have been removed
print("Dataframe after removing unnamed columns:\n", df.head())

Dataframe before removing unnamed columns:
    Unnamed: 0     Id     Name  Year Gender State  Count
0       11349  11350     Emma  2004      F    AK     62
1       11350  11351  Madison  2004      F    AK     48
2       11351  11352   Hannah  2004      F    AK     46
3       11352  11353    Grace  2004      F    AK     44
4       11353  11354    Emily  2004      F    AK     41
Dataframe after removing unnamed columns:
       Id     Name  Year Gender State  Count
0  11350     Emma  2004      F    AK     62
1  11351  Madison  2004      F    AK     48
2  11352   Hannah  2004      F    AK     46
3  11353    Grace  2004      F    AK     44
4  11354    Emily  2004      F    AK     41

In [15]:
#Question 2: Show the distribution of male and female

#Group by Gender column and sum the values in Count column to get the distribution of male and female
print("The distribution of Male and Female is:\n", df.groupby(['Gender']).sum()['Count'])

The distribution of Male and Female is:
 Gender
F    16380293
M    19041199
Name: Count, dtype: int64

In [27]:
#Question 3: Show the top 5 most preferred names

#Group by Name column and sume the values in Count column to get the total count for each name. Also, apply sorting on the Count column and reset the index
namedf = df.groupby(['Name']).sum().sort_values(by=['Count'],ascending=False).reset_index()

#Display the top 5 most preferred names
print("The top 5 most preferred names are:\n", namedf['Name'].head())

The top 5 most preferred names are:
 0       Jacob
1        Emma
2     Michael
3       Ethan
4    Isabella
Name: Name, dtype: object

In [44]:
#Question 4: The median name occurence in the dataset

#Use the mode function on name column to find the median name
name = df.loc[:,"Name"].mode()

#Get the value of median name as str
n = name.iloc[0]

#Filter the dataframe by median name and count the occurrence of median name
df1 = df[df["Name"] == n].groupby("Name").count().reset_index()

#Display the median name occurrence in the dataset
print("The median name occurrence in dataset is:\n", df1[['Name','Count']])

The median name occurrence in dataset is:
     Name  Count
0  Riley   1112

In [95]:
#Question 5: Distribution of male and female born count by states

#Group the data by State and Gender column and sum the values. Also, reset the index
df1 = df.groupby(['State','Gender']).sum().reset_index()

#Display the distribuion of male and female born count by states
print("Distribution of male and femail born count by State:\n", df1[['State', 'Gender','Count']])

Distribution of male and femail born count by State:
     State Gender    Count
0      AK      F    26250
1      AK      M    37399
2      AL      F   215308
3      AL      M   260114
4      AR      F   129712
5      AR      M   162947
6      AZ      F   368567
7      AZ      M   439691
8      CA      F  2414063
9      CA      M  2670584
10     CO      F   260805
11     CO      M   313425
12     CT      F   141350
13     CT      M   171397
14     DC      F    35276
15     DC      M    47228
16     DE      F    31312
17     DE      M    41748
18     FL      F   915422
19     FL      M  1060957
20     GA      F   549637
21     GA      M   635531
22     HI      F    37279
23     HI      M    53127
24     IA      F   144764
25     IA      M   174009
26     ID      F    72808
27     ID      M    94320
28     IL      F   695312
29     IL      M   791679
..    ...    ...      ...
72     OK      F   184967
73     OK      M   228613
74     OR      F   172111
75     OR      M   209445
76     PA      F   593382
77     PA      M   682709
78     RI      F    35560
79     RI      M    47939
80     SC      F   197917
81     SC      M   237442
82     SD      F    34104
83     SD      M    45443
84     TN      F   336487
85     TN      M   398615
86     TX      F  1786281
87     TX      M  2005394
88     UT      F   202892
89     UT      M   245324
90     VA      F   405503
91     VA      M   466873
92     VT      F    15079
93     VT      M    21353
94     WA      F   334944
95     WA      M   395377
96     WI      F   264921
97     WI      M   311758
98     WV      F    73800
99     WV      M    93557
100    WY      F    14107
101    WY      M    21912

[102 rows x 3 columns]

In [57]:
help(df.groupby)

Help on method groupby in module pandas.core.generic:

groupby(by=None, axis=0, level=None, as_index=True, sort=True, group_keys=True, squeeze=False, observed=False, **kwargs) method of pandas.core.frame.DataFrame instance
    Group DataFrame or Series using a mapper or by a Series of columns.

    A groupby operation involves some combination of splitting the
    object, applying a function, and combining the results. This can be
    used to group large amounts of data and compute operations on these
    groups.

    Parameters
    ----------
    by : mapping, function, label, or list of labels
        Used to determine the groups for the groupby.
        If ``by`` is a function, it's called on each value of the object's
        index. If a dict or Series is passed, the Series or dict VALUES
        will be used to determine the groups (the Series' values are first
        aligned; see ``.align()`` method). If an ndarray is passed, the
        values are used as-is determine the groups. A label or list of
        labels may be passed to group by the columns in ``self``. Notice
        that a tuple is interpreted a (single) key.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Split along rows (0) or columns (1).
    level : int, level name, or sequence of such, default None
        If the axis is a MultiIndex (hierarchical), group by a particular
        level or levels.
    as_index : bool, default True
        For aggregated output, return object with group labels as the
        index. Only relevant for DataFrame input. as_index=False is
        effectively "SQL-style" grouped output.
    sort : bool, default True
        Sort group keys. Get better performance by turning this off.
        Note this does not influence the order of observations within each
        group. Groupby preserves the order of rows within each group.
    group_keys : bool, default True
        When calling apply, add group keys to index to identify pieces.
    squeeze : bool, default False
        Reduce the dimensionality of the return type if possible,
        otherwise return a consistent type.
    observed : bool, default False
        This only applies if any of the groupers are Categoricals.
        If True: only show observed values for categorical groupers.
        If False: show all values for categorical groupers.

        .. versionadded:: 0.23.0

    **kwargs
        Optional, only accepts keyword argument 'mutated' and is passed
        to groupby.

    Returns
    -------
    DataFrameGroupBy or SeriesGroupBy
        Depends on the calling object and returns groupby object that
        contains information about the groups.

    See Also
    --------
    resample : Convenience method for frequency conversion and resampling
        of time series.

    Notes
    -----
    See the `user guide
    <http://pandas.pydata.org/pandas-docs/stable/groupby.html>`_ for more.

    Examples
    --------
    >>> df = pd.DataFrame({'Animal' : ['Falcon', 'Falcon',
    ...                                'Parrot', 'Parrot'],
    ...                    'Max Speed' : [380., 370., 24., 26.]})
    >>> df
       Animal  Max Speed
    0  Falcon      380.0
    1  Falcon      370.0
    2  Parrot       24.0
    3  Parrot       26.0
    >>> df.groupby(['Animal']).mean()
            Max Speed
    Animal
    Falcon      375.0
    Parrot       25.0

    **Hierarchical Indexes**

    We can groupby different levels of a hierarchical index
    using the `level` parameter:

    >>> arrays = [['Falcon', 'Falcon', 'Parrot', 'Parrot'],
    ...           ['Capitve', 'Wild', 'Capitve', 'Wild']]
    >>> index = pd.MultiIndex.from_arrays(arrays, names=('Animal', 'Type'))
    >>> df = pd.DataFrame({'Max Speed' : [390., 350., 30., 20.]},
    ...                    index=index)
    >>> df
                    Max Speed
    Animal Type
    Falcon Capitve      390.0
           Wild         350.0
    Parrot Capitve       30.0
           Wild          20.0
    >>> df.groupby(level=0).mean()
            Max Speed
    Animal
    Falcon      370.0
    Parrot       25.0
    >>> df.groupby(level=1).mean()
             Max Speed
    Type
    Capitve      210.0
    Wild         185.0